name: arina
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  
  cloud_firestore: ^4.15.8
  day_night_time_picker: ^1.3.0+1
  easy_date_timeline: ^1.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.9
  go_router: ^13.2.1
  image_picker: ^1.0.7
  ionicons: ^0.2.2
  open_filex: ^4.4.0
  path_provider: ^2.1.1
  provider: ^6.1.2
  readmore: ^2.2.0
  uuid: ^4.3.3

  latlong2: any
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_map_cached_tile_provider: ^0.0.2
  google_places_autocomplete_text_field: ^0.1.3
  google_maps_flutter: ^2.6.0
  http: any
  dropdown_button2: ^2.3.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/homeradar.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
adaptive_icon_background: "#222222"
adaptive_icon_foreground: "assets/png/homeradar_round.png"
 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/3ds/
    - assets/png/
    - assets/svg/
    - assets/svg/Group.svg
    - assets/images/
    - assets/images/person/
    - assets/images/thumbnails/
    - assets/images/products/
    
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_7pt-Regular.ttf
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio-Regular.ttf