name: arina
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  
  day_night_time_picker: ^1.3.0+1
  easy_date_timeline: ^1.0.5
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  ionicons: ^0.2.2
  open_filex: ^4.4.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  readmore: ^2.2.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/3ds/
    - assets/images/
    - assets/images/products/
    - assets/images/person/
    - assets/images/thumbnails/
    - assets/svg/
    - assets/png/
    - assets/svg/Group.svg
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_7pt-Regular.ttf
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio-Regular.ttf